# Generated by Django 3.0.8 on 2020-07-11 10:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielens.Audience')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielens.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielens.Audience')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielens.Movie')),
            ],
        ),
    ]
