# Generated by Django 3.0.8 on 2020-07-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielens', '0002_auto_20200711_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='audience',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=255),
        ),
    ]
